name = "tuerqi"
main = "src/index.js"
compatibility_date = "2026-05-05"

[triggers]
crons = ["0 0 * * *", "0 6 * * *"]

[vars]
SEAGM_URL = "https://www.seagm.com/zh-cn/itunes-gift-card-turkey?item_id=16820"
DENOMS = "500,1000,2000"
RETENTION_DAYS = "60"
MAX_HISTORY_RECORDS = "500"

[[kv_namespaces]]
binding = "PRICE_HISTORY"
id = "99ec8198359743f8a4840e523d431ebc"
